//
//  SignupConstants.swift
//  AimHigh
//
//  Created by Jordy Vazquez on 3/31/21.
//  Copyright © 2021 Jordy Vazquez. All rights reserved.
//

import Foundation

struct SignupConstants {
    static let firstNameMinLength = 2
    static let firstNameMaxLength = 10
    static let lastNameMinLength = 6
    static let lastNameMaxLength = 20
    static let passwordMinLength = 6
    static let passwordMaxLength = 20
}

struct GoalFormConstants {
    static let nameOfGoalMinLength = 4
    static let nameOfGoalMaxLength = 30
    static let reasonsForGoalMinLength = 6
    static let reasonsForGoalMaxLength = 25
//    Let work on date and document ID later on. Document ID comes from Firebase or is generated by them
//   static let date
//   static var documentID
}
